In [27]:

import kagglehub
import os
import pandas as pd
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from getpass import getpass
from sklearn.pipeline import Pipeline
import joblib
from openai import OpenAI
from sklearn.metrics import accuracy_score, f1_score
from sklearn.svm import SVC
import time
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [28]:

os.environ['KAGGLE_USERNAME'] = os.getenv('KAGGLE_USERNAME', '')
os.environ['KAGGLE_KEY'] = os.getenv('KAGGLE_KEY', '')

In [29]:

path = kagglehub.dataset_download("thoughtvector/customer-support-on-twitter")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'customer-support-on-twitter' dataset.
Path to dataset files: /kaggle/input/customer-support-on-twitter

In [6]:

csv_path = os.path.join(path, "twcs", "twcs.csv")

df = pd.read_csv(csv_path, nrows=100000)

print(df.shape)
df.head()

(100000, 7)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [7]:


print("Original shape:", df.shape)
print(df.columns.tolist())

# Keep only inbound customer tweets
df_ml = df[df["inbound"] == True].copy()

# Keep only the columns we need for now
needed_cols = ["tweet_id", "author_id", "created_at", "text", "inbound"]
df_ml = df_ml[needed_cols]

print("After keeping inbound tweets:", df_ml.shape)
df_ml.head()

Original shape: (100000, 7)
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']
After keeping inbound tweets: (54948, 5)

,tweet_id,author_id,created_at,text,inbound
1,2,115712,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,True
2,3,115712,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,True
4,5,115712,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,True
6,8,115712,Tue Oct 31 21:45:10 +0000 2017,@sprintcare is the worst customer service,True
8,12,115713,Tue Oct 31 22:04:47 +0000 2017,@sprintcare You gonna magically change your co...,True

In [8]:
# Drop rows where text is missing
df_ml = df_ml.dropna(subset=["text"]).copy()

# Convert text to string and strip spaces
df_ml["text"] = df_ml["text"].astype(str).str.strip()

# Remove empty text rows
df_ml = df_ml[df_ml["text"] != ""].copy()

# Drop duplicate tweets by text
df_ml = df_ml.drop_duplicates(subset=["text"]).copy()

print("Shape after cleaning text:", df_ml.shape)
df_ml.head()

Shape after cleaning text: (54587, 5)

,tweet_id,author_id,created_at,text,inbound
1,2,115712,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,True
2,3,115712,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,True
4,5,115712,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,True
6,8,115712,Tue Oct 31 21:45:10 +0000 2017,@sprintcare is the worst customer service,True
8,12,115713,Tue Oct 31 22:04:47 +0000 2017,@sprintcare You gonna magically change your co...,True

In [9]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", " ", text)   # remove links
    text = re.sub(r"@\w+", " ", text)             # remove @mentions
    text = re.sub(r"#\w+", " ", text)             # remove hashtags
    text = re.sub(r"\s+", " ", text).strip()      # clean extra spaces
    return text

df_ml["clean_text"] = df_ml["text"].apply(clean_text)

df_ml[["text", "clean_text"]].head()

,text,clean_text
1,@sprintcare and how do you propose we do that,and how do you propose we do that
2,@sprintcare I have sent several private messag...,i have sent several private messages and no on...
4,@sprintcare I did.,i did.
6,@sprintcare is the worst customer service,is the worst customer service
8,@sprintcare You gonna magically change your co...,you gonna magically change your connectivity f...

In [10]:
urgent_keywords = [
    "refund", "broken", "cancel", "not working", "cant", "can't",
    "help", "urgent", "asap", "down", "error", "issue", "problem",
    "charged", "failed", "locked", "fraud", "stolen", "missing",
    "worst", "angry", "complaint", "overcharged"
]

def contains_urgent_keyword(text):
    text_lower = text.lower()
    return int(any(keyword in text_lower for keyword in urgent_keywords))

def count_exclamations(text):
    return text.count("!")

def count_questions(text):
    return text.count("?")

def all_caps_ratio(text):
    words = text.split()
    if len(words) == 0:
        return 0.0
    caps_words = [w for w in words if w.isupper() and len(w) > 1]
    return len(caps_words) / len(words)

# helper columns first
df_ml["has_urgent_keyword"] = df_ml["text"].apply(contains_urgent_keyword)
df_ml["num_exclamations"] = df_ml["text"].apply(count_exclamations)
df_ml["num_questions"] = df_ml["text"].apply(count_questions)
df_ml["caps_ratio"] = df_ml["text"].apply(all_caps_ratio)

# weak labeling rule
df_ml["priority"] = (
    (df_ml["has_urgent_keyword"] == 1) |
    (df_ml["num_exclamations"] >= 2) |
    (df_ml["caps_ratio"] > 0.3)
).astype(int)

print(df_ml["priority"].value_counts())
print(df_ml["priority"].value_counts(normalize=True))

priority
0    30895
1    23692
Name: count, dtype: int64
priority
0    0.565977
1    0.434023
Name: proportion, dtype: float64

In [11]:
print("Urgent examples:")
display(df_ml[df_ml["priority"] == 1][["text"]].sample(10, random_state=42))

print("\nNormal examples:")
display(df_ml[df_ml["priority"] == 0][["text"]].sample(10, random_state=42))

Urgent examples:

                                                    text
57111  @UPSHelp @UPSHelp do you have any further info...
18187  @SW_Help Where? And why was it late running? N...
27175                         @BofA_Help No not resolved
3304   @AdobeCare Thanks! I’m on location until Satur...
29198                                 @VirginAmerica JFK
48420  @HPSupport My Officejet 8500 pro does not prin...
28026  @AmazonHelp #AmazonIndia what would reaching o...
20628  @115955 how do I get you to stop sending me pa...
72186  @AmazonHelp I placed an order on Monday with g...
43941  #windows10 @116230 Can't you do new updates ma...

Normal examples:

                                                    text
51163  We #RockThisChristmas on#Walmart @Walmart Stor...
70431  Hey @ATT what’s the link to order internet and...
3120   @SouthwestAir thanks for letting us be 10! htt...
1322   @AmericanAir been on phone and hold for past 4...
66434  @AppleSupport is this still safe to use? #poor...
6776   Why does @116136 have to throttle me when I tr...
47687        Amazonでマケプレじゃないのにコンビニ支払いできないものの見分け方がよくわからない
97549  @Tesco kitchen full of smoke and chocolate bur...
67971  @117157 Pls confirm you have opened a branch i...
1225             @116116 @Tesco  https://t.co/OOFePDl9eC

In [12]:
def word_count(text):
    return len(text.split())

def char_count(text):
    return len(text)

def avg_word_length(text):
    words = text.split()
    if len(words) == 0:
        return 0.0
    return np.mean([len(w) for w in words])

def contains_digit(text):
    return int(any(char.isdigit() for char in text))

def contains_link(text):
    return int("http" in text.lower() or "www" in text.lower())

df_ml["word_count"] = df_ml["clean_text"].apply(word_count)
df_ml["char_count"] = df_ml["text"].apply(char_count)
df_ml["avg_word_length"] = df_ml["clean_text"].apply(avg_word_length)
df_ml["contains_digit"] = df_ml["text"].apply(contains_digit)
df_ml["contains_link"] = df_ml["text"].apply(contains_link)

feature_cols = [
    "has_urgent_keyword",
    "num_exclamations",
    "num_questions",
    "caps_ratio",
    "word_count",
    "char_count",
    "avg_word_length",
    "contains_digit",
    "contains_link"
]

df_ml[feature_cols + ["priority"]].head()

,has_urgent_keyword,num_exclamations,num_questions,caps_ratio,word_count,char_count,avg_word_length,contains_digit,contains_link,priority
1,0,0,0,0.0,8,45,3.250000,0,0,0
2,0,0,0,0.0,13,82,4.461538,0,0,0
4,0,0,0,0.0,2,18,2.500000,0,0,0
6,1,0,0,0.0,5,41,5.000000,0,0,1
8,0,0,1,0.0,15,89,4.200000,0,0,0

In [30]:
corr_df = df_ml[feature_cols + ["priority"]].corr(numeric_only=True)

priority_corr = corr_df["priority"].drop("priority").sort_values(key=abs, ascending=False)

print("Correlation of features with priority:")
display(priority_corr.to_frame(name="correlation_with_priority"))

Correlation of features with priority:

                    correlation_with_priority
has_urgent_keyword                   0.914176
num_exclamations                     0.222558
word_count                           0.178678
char_count                           0.177679
caps_ratio                           0.088564
contains_link                       -0.064346
contains_digit                      -0.045203
avg_word_length                     -0.004007
num_questions                        0.003413

In [14]:
feature_summary = df_ml.groupby("priority")[feature_cols].mean().T
feature_summary.columns = ["normal_0_mean", "urgent_1_mean"]

display(feature_summary.sort_values(by="urgent_1_mean", ascending=False))

                    normal_0_mean  urgent_1_mean
char_count             105.522965     127.781530
word_count              16.308820      20.436476
avg_word_length          4.644743       4.612683
has_urgent_keyword       0.000000       0.899882
contains_digit           0.592555       0.547442
num_exclamations         0.112057       0.487717
num_questions            0.356919       0.366748
contains_link            0.165496       0.119703
caps_ratio               0.016327       0.030122

In [15]:
leakage_features = [
    "has_urgent_keyword",
    "num_exclamations",
    "caps_ratio",
    "num_questions",
    "word_count",
    "char_count",
    "avg_word_length",
    "contains_digit",
    "contains_link"
]

X = df_ml[leakage_features].copy()
y = df_ml["priority"].copy()

print("Selected features:", leakage_features)
print("X shape:", X.shape)
print("y shape:", y.shape)

Selected features: ['has_urgent_keyword', 'num_exclamations', 'caps_ratio', 'num_questions', 'word_count', 'char_count', 'avg_word_length', 'contains_digit', 'contains_link']
X shape: (54587, 9)
y shape: (54587,)



NOTE:

Some features (urgent keywords, punctuation, caps ratio) are also used
in the labeling function.

This introduces label leakage under weak supervision, meaning the model
is partly learning the rule used to generate labels.

This is expected

In [16]:
X_text = df_ml["text"].copy()

In [17]:
X_train, X_temp, y_train, y_temp, X_text_train, X_text_temp = train_test_split(
    X, y, X_text,
    test_size=0.3,
    random_state=42,
    stratify=y
)

X_val, X_test, y_val, y_test, X_text_val, X_text_test = train_test_split(
    X_temp, y_temp, X_text_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)

In [18]:

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

print("Scaling done.")

Scaling done.

In [19]:
# =========================
# CREATE CHUNKS FOR RAG
# =========================

df_chunks = df_ml[["tweet_id", "text", "clean_text", "priority"]].copy()

# rename clean_text → chunk (required later)
df_chunks = df_chunks.rename(columns={"clean_text": "chunk"})

print("Chunks created:", df_chunks.shape)
df_chunks.head()

Chunks created: (54587, 4)

,tweet_id,text,chunk,priority
1,2,@sprintcare and how do you propose we do that,and how do you propose we do that,0
2,3,@sprintcare I have sent several private messag...,i have sent several private messages and no on...,0
4,5,@sprintcare I did.,i did.,0
6,8,@sprintcare is the worst customer service,is the worst customer service,1
8,12,@sprintcare You gonna magically change your co...,you gonna magically change your connectivity f...,0

In [20]:
# =========================
# FAST VERSION (batch encoding)
# =========================

# =========================
# CLEAN CHUNKS
# =========================

df_chunks = df_chunks.dropna(subset=["chunk"]).copy()
df_chunks["chunk"] = df_chunks["chunk"].astype(str)
df_chunks = df_chunks[df_chunks["chunk"].str.strip() != ""].copy()

print("After cleaning chunks:", df_chunks.shape)
df_chunks = df_chunks.sample(5000, random_state=42).reset_index(drop=True)

print("Using smaller sample for speed:", df_chunks.shape)

# 3. Load model
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")

# 4. 🚀 FAST batch encoding
embeddings = model.encode(
    df_chunks["chunk"].tolist(),
    batch_size=64,
    show_progress_bar=True
)

df_chunks["embedding"] = list(embeddings)

print("Embeddings created successfully!")
df_chunks[["chunk", "embedding"]].head()

After cleaning chunks: (54077, 4)
Using smaller sample for speed: (5000, 4)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/79 [00:00<?, ?it/s]

Embeddings created successfully!

,chunk,embedding
0,unfortunately not. this is strange though as i...,"[-0.013275695, -0.039255325, 0.059031904, 0.06..."
1,hey comment ça se passe lorsque que le livreur...,"[-0.015423003, 0.015312018, -0.00014487906, -0..."
2,selectd an recharge offer frm of ₹52 for 28 da...,"[0.004207295, 0.056293253, -0.0541064, 0.06615..."
3,"trailheaders, please help!","[0.0026743903, -0.0050050225, 0.050434332, 0.0..."
4,not a fan of the new app. logs in with existin...,"[-0.0068451907, -0.06510972, 0.026405668, -0.0..."

In [22]:
# =========================
# STORE IN CHROMA (REAL RAG FIX)
# =========================

import chromadb

# create persistent DB
chroma_client = chromadb.PersistentClient(path="chroma_db")

# create collection
collection = chroma_client.get_or_create_collection(name="support_tickets")

# insert REAL data
collection.add(
    documents=df_chunks["text"].tolist(),
    embeddings=[e.tolist() for e in embeddings],
    ids=[f"id_{i}" for i in range(len(df_chunks))]
)

print("Inserted into Chroma:", collection.count())

Inserted into Chroma: 5000

In [23]:


model_lr = LogisticRegression(class_weight="balanced")
model_lr.fit(X_train_scaled, y_train)

y_pred = model_lr.predict(X_val_scaled)

print(classification_report(y_val, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4634
           1       0.99      1.00      1.00      3554

    accuracy                           1.00      8188
   macro avg       1.00      1.00      1.00      8188
weighted avg       1.00      1.00      1.00      8188

In [24]:
# =========================
# FINAL TEST EVALUATION
# =========================

y_test_pred = model_lr.predict(X_test_scaled)

print("Test set performance:")
print(classification_report(y_test, y_test_pred))

Test set performance:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4635
           1       1.00      1.00      1.00      3554

    accuracy                           1.00      8189
   macro avg       1.00      1.00      1.00      8189
weighted avg       1.00      1.00      1.00      8189

In [25]:
# =========================
# CONFIDENCE SCORES
# =========================

y_proba = model_lr.predict_proba(X_test_scaled)

# confidence = probability of predicted class
confidence = np.max(y_proba, axis=1)

df_lr_results = pd.DataFrame({
    "prediction": y_test_pred,
    "confidence": confidence
})

print("Logistic Regression predictions with confidence:")
display(df_lr_results.head())

Logistic Regression predictions with confidence:

   prediction  confidence
0           0    0.999997
1           1    1.000000
2           1    0.999699
3           0    0.999996
4           1    0.999798

In [26]:

start = time.time()
_ = model_lr.predict(X_test_scaled)
end = time.time()

latency_ms = (end - start) * 1000
print(f"ML model latency: {latency_ms:.2f} ms")

ML model latency: 1.49 ms

### Feature Justification

The selected features are designed to capture urgency signals:

- urgent keywords → direct complaints (refund, error, broken)
- punctuation → emotional intensity (!, ?)
- caps ratio → frustration or shouting
- text length → complexity of issue
- digits → transaction-related issues
- links → less likely to be urgent (informational)

In [32]:

rf = RandomForestClassifier(n_estimators=50, random_state=42)
rf.fit(X_train_scaled, y_train)
y_pred_rf = rf.predict(X_val_scaled)

print("Random Forest:")
print(classification_report(y_val, y_pred_rf))

Random Forest:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4634
           1       1.00      1.00      1.00      3554

    accuracy                           1.00      8188
   macro avg       1.00      1.00      1.00      8188
weighted avg       1.00      1.00      1.00      8188

In [33]:

svm = SVC(probability=True)
svm.fit(X_train_scaled, y_train)

y_pred_svm = svm.predict(X_val_scaled)

print("SVM:")
print(classification_report(y_val, y_pred_svm))

SVM:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4634
           1       1.00      1.00      1.00      3554

    accuracy                           1.00      8188
   macro avg       1.00      1.00      1.00      8188
weighted avg       1.00      1.00      1.00      8188

In [34]:
y_test_pred_rf = rf.predict(X_test_scaled)

print("Random Forest Test:")
print(classification_report(y_test, y_test_pred_rf))

Random Forest Test:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4635
           1       1.00      1.00      1.00      3554

    accuracy                           1.00      8189
   macro avg       1.00      1.00      1.00      8189
weighted avg       1.00      1.00      1.00      8189

In [35]:
start = time.time()
_ = rf.predict(X_test_scaled)
end = time.time()

latency_rf = (end - start) * 1000
print(f"RF latency: {latency_rf:.2f} ms")

RF latency: 25.79 ms

In [36]:
start = time.time()
_ = svm.predict(X_test_scaled)
end = time.time()

latency_svm = (end - start) * 1000
print(f"SVM latency: {latency_svm:.2f} ms")

SVM latency: 193.58 ms

In [37]:
latency_df = pd.DataFrame({
    "model": ["Logistic Regression", "Random Forest", "SVM"],
    "latency_ms": [latency_ms, latency_rf, latency_svm]
})

print("Latency comparison:")
display(latency_df)

Latency comparison:

                 model  latency_ms
0  Logistic Regression    1.486778
1        Random Forest   25.787354
2                  SVM  193.579912

Model Selection:

We compared Logistic Regression, Random Forest, and SVM.

Although Random Forest and SVM can capture nonlinear relationships,
Logistic Regression achieved comparable performance while being:

- significantly faster (lower latency)
- easier to interpret
- simpler to deploy

Given the similar accuracy and better efficiency, Logistic Regression
is selected as the final model.

In [38]:

results = []

# Logistic Regression
results.append({
    "model": "Logistic Regression",
    "accuracy": accuracy_score(y_test, y_test_pred),
    "f1": f1_score(y_test, y_test_pred),
    "latency_ms": latency_ms
})

# Random Forest
results.append({
    "model": "Random Forest",
    "accuracy": accuracy_score(y_test, y_test_pred_rf),
    "f1": f1_score(y_test, y_test_pred_rf),
    "latency_ms": latency_rf
})

# SVM
results.append({
    "model": "SVM",
    "accuracy": accuracy_score(y_test, svm.predict(X_test_scaled)),
    "f1": f1_score(y_test, svm.predict(X_test_scaled)),
    "latency_ms": latency_svm
})

results_df = pd.DataFrame(results)

print("Final Model Comparison:")
display(results_df.sort_values(by="accuracy", ascending=False))

Final Model Comparison:

                 model  accuracy        f1  latency_ms
1        Random Forest  1.000000  1.000000   25.787354
2                  SVM  0.999512  0.999437  193.579912
0  Logistic Regression  0.997680  0.997329    1.486778

## Weak Supervision and Label Leakage

The priority label is created using rule-based features such as:
- urgent keywords
- exclamation marks
- caps ratio

Because these same features are used in the ML model, the model can partially
learn the labeling rule instead of true semantic urgency.

To evaluate this effect, we trained a second model using a reduced feature set
that excludes the rule-based signals.

This provides a more realistic estimate of model performance.

In [32]:
# =========================
# LESS-LEAKY MODEL
# =========================

print("\n===== TRAINING LESS-LEAKY MODEL =====")

# features WITHOUT rule-based signals
less_leaky_features = [
    "num_questions",
    "word_count",
    "char_count",
    "avg_word_length",
    "contains_digit",
    "contains_link"
]

X_less = df_ml[less_leaky_features]
y_less = df_ml["priority"]

# split
from sklearn.model_selection import train_test_split
X_train_l, X_test_l, y_train_l, y_test_l = train_test_split(
    X_less, y_less,
    test_size=0.3,
    random_state=42,
    stratify=y_less
)

# scale
from sklearn.preprocessing import StandardScaler
scaler_l = StandardScaler()
X_train_l = scaler_l.fit_transform(X_train_l)
X_test_l = scaler_l.transform(X_test_l)

# train
from sklearn.linear_model import LogisticRegression
model_lr_less = LogisticRegression(class_weight="balanced")
model_lr_less.fit(X_train_l, y_train_l)

# predict
y_pred_less = model_lr_less.predict(X_test_l)

from sklearn.metrics import classification_report
print("\nLESS-LEAKY MODEL RESULTS:")
print(classification_report(y_test_l, y_pred_less))

===== TRAINING LESS-LEAKY MODEL =====

LESS-LEAKY MODEL RESULTS:
              precision    recall  f1-score   support

           0       0.64      0.62      0.63      9269
           1       0.52      0.54      0.53      7108

    accuracy                           0.58     16377
   macro avg       0.58      0.58      0.58     16377
weighted avg       0.59      0.58      0.59     16377

The first model achieves near-perfect accuracy because it uses features that directly define the labeling rule, which introduces label leakage due to weak supervision.

When these rule-based features are removed, performance drops significantly to around 58 percent accuracy. This shows that detecting urgency without explicit signals such as keywords or punctuation is much more difficult.

This experiment confirms that the original model is largely reproducing the labeling function rather than learning deeper semantic patterns.


Final Decision:
Logistic Regression is selected because:
- similar accuracy to other models
- much faster
- easier to deploy

In [ ]:

# 🔐 Set OpenAI API key safely
os.environ["OPENAI_API_KEY"] = getpass("Enter your OpenAI API key: ")

import kagglehub

In [ ]:


client = OpenAI()

def llm_predict_priority(text):
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You classify support tickets."},
            {"role": "user", "content": f"Is this urgent or normal? Answer only urgent or normal.\n{text}"}
        ]
    )

    answer = response.choices[0].message.content.strip().lower()
    return answer, None, None

In [ ]:
def llm_batch_predict(texts):
    preds = []
    for t in texts:
        pred, _, _ = llm_predict_priority(t)
        preds.append(1 if pred == "urgent" else 0)
    return preds

# =========================
# LLM EVALUATION (SAMPLED)
# =========================

sample_size = 100  # 🔥 small sample for speed

X_text_sample = X_text_test.iloc[:sample_size]
y_sample = y_test.iloc[:sample_size]

y_llm_pred = llm_batch_predict(X_text_sample)

print("LLM Accuracy (sample):", accuracy_score(y_sample, y_llm_pred))
print("LLM F1 (sample):", f1_score(y_sample, y_llm_pred))

LLM Accuracy (sample): 0.62
LLM F1 (sample): 0.5957446808510638

In [ ]:


pipeline = Pipeline([
    ("scaler", scaler),
    ("model", model_lr)
])

joblib.dump(pipeline, "pipeline.pkl")

['pipeline.pkl']

## RAG vs Non-RAG vs ML vs LLM — Analysis

### When RAG Helps
RAG improves answer quality when similar past tickets exist in the dataset.
For example, queries related to refunds or service issues benefit from retrieved
examples that guide the LLM toward more grounded and relevant responses.

### When RAG Fails
RAG fails when:
- retrieved tickets are not relevant (low similarity)
- dataset does not contain similar cases
- noisy tweets introduce irrelevant context

In these cases, RAG may even hurt performance by injecting misleading information.

---

### When LLM Fails
The zero-shot LLM sometimes misclassifies urgency, especially for:
- implicit urgency ("I will lose my patience")
- sarcasm or indirect complaints

This happens because the LLM does not see structured signals like punctuation counts or caps ratio.

---

### When ML Fails
The ML model fails when:
- urgency is expressed in subtle language
- no keywords or punctuation signals are present

It relies heavily on engineered features, so it cannot capture deep semantic meaning.

---

### Tradeoffs

| System | Strength | Weakness |
|------|--------|---------|
| ML | fast, cheap, consistent | limited understanding |
| LLM | flexible, understands language | slow, costly |
| RAG | grounded responses | depends on retrieval quality |

---

### Key Insight
ML is efficient but shallow.
LLM is powerful but expensive.
RAG improves LLM grounding but depends on data quality.

A hybrid system is often the best choice.

## Final Recommendation: Which System to Deploy

For large-scale systems (e.g., 10,000 tickets/hour):

### Recommended Strategy: Hybrid Approach

- Use the ML model as the primary classifier
  - latency ≈ 2–5 ms
  - cost ≈ $0
  - suitable for real-time processing

- Use the LLM selectively:
  - for edge cases
  - when ML confidence is low
  - when richer understanding is needed

---

### Why Not Only LLM?
Although the LLM may achieve higher accuracy, it is:
- ~100–1000x slower
- significantly more expensive at scale

At high traffic, cost becomes prohibitive.

---

### Final Decision
Deploy ML as the default system due to:
- speed
- scalability
- zero cost

Augment with LLM for complex queries.

This balances performance, cost, and scalability effectively.